preload = ~/Pictures/Wallpapers/wallpaperflare.com_wallpaper_upscayl_1x_digital-art-4x.png
wallpaper = HDMI-A-1, ~/Pictures/Wallpapers/wallpaperflare.com_wallpaper_upscayl_1x_digital-art-4x.png
wallpaper = eDP-1, ~/Pictures/Wallpapers/wallpaperflare.com_wallpaper_upscayl_1x_digital-art-4x.png
splash = off
ipc = off
